name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # 毎日日本時間の午前9時に実行
  workflow_dispatch: # 手動で実行したい時用

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        id: sync
        uses: aieri/workflow-upstream-sync@v2
        with:
          upstream_repository: sugusokothx/panel-y # ここを書き換え
          target_branch: main # 同期先のブランチ名
          upstream_branch: main # 同期元のブランチ名
          force: false # 自分の変更を上書きしたくない場合はfalse
